# Path to samplesheet
samplesheet: samples.csv

# Directory containing fastq files
fastq_dir: fastqs/

# Directory for outputs
output_dir: outs/

# Specify Bowtie2 reference genome
reference: assets/reference/Homo_sapiens/NCBI/GRCh38/Sequence/Bowtie2Index/chr21
chrom_sizes: assets/reference/Homo_sapiens/NCBI/GRCh38/chrom.sizes

# Specify reference genome if using spike-in DNA (usually E. coli)
# This automatically normalizes to the sequencing depth of the spike-in. Leave blank to normalize to sequencing depth of the sample.
reference_spikein: assets/reference/Escherichia_coli_K_12_MG1655/NCBI/2001-10-15/Sequence/Bowtie2Index/genome

# List of excluded genome regions to filter from peaks files
exclusion_list: assets/exclusion_list_nordin_et_al_2023_hg38.bed

# Threads per job for some mulithreaded jobs
threads: 4

# Illumina adaptors to be trimmed
adaptor_5p: AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
adaptor_3p: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
# Minimum length of read after trimming
min_len: 20
