name: cutnrun-snakemake
channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake>=5.14.0,<8
  - biopython>=1.74
  - bedtools>=2.29.2
  - pandas>=1.0.5
  - fastqc>=0.11.8
  - cutadapt>=2.4
  - picard>=2.20.7
  - bowtie2>=2.4.1
  - ucsc-bedgraphtobigwig>=377
  - samtools>=1.10
  - macs2>=2.2.7.1
  - seacr>=1.3
  - awscli>=1.18.127
  - deeptools>=3.5.1
  - r-base
  - r-knitr
  - r-tidyverse
